name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.12.0'

      - name: Verify Cypress
        run: npx cypress verify

      - name: Install Cypress
        run: npm install cypress --save-dev


      - name: Install Dependencies
        run: npm ci

      - name: Upload npm debug log
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-log
          path: /home/runner/.npm/_logs/*.log

      - name: Run Cypress Tests
        run: npx cypress run

